// --- CONSTANTS ---
const DOCUMENT_VERSIONS_CLASSIFICATION = Object.freeze({
    UNCLASSIFIED: 'UNCLASSIFIED',
    PUBLIC: 'PUBLIC',
    PRIVATE: 'PRIVATE',
    CONFIDENTIAL: 'CONFIDENTIAL',
    RESTRICTED: 'RESTRICTED',
});

module.exports = {
    DOCUMENT_VERSIONS_CLASSIFICATION,
};
