// --- EVENTS CONSTANTS ---
export const EVENTS = Object.freeze({
    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_LOGOUT: 'AUTH_LOGOUT',

    DEPARTMENT_CREATED: 'DEPARTMENT_CREATED',
    DEPARTMENT_UPDATED: 'DEPARTMENT_UPDATED',
    DEPARTMENT_DELETED: 'DEPARTMENT_DELETED',

    USER_CREATED: 'USER_CREATED',
    USER_UPDATED: 'USER_UPDATED',
    USER_SUSPENDED: 'USER_SUSPENDED',
    USER_UNSUSPENDED: 'USER_UNSUSPENDED',

    DOCUMENT_CREATED: 'DOCUMENT_CREATED',
    DOCUMENT_UPDATED: 'DOCUMENT_UPDATED',
    DOCUMENT_DELETED: 'DOCUMENT_DELETED',
    DOCUMENT_ARCHIVED: 'DOCUMENT_ARCHIVED',
    DOCUMENT_RESTORED: 'DOCUMENT_RESTORED',
    DOCUMENT_SHARED: 'DOCUMENT_SHARED',
    DOCUMENT_UNSHARED: 'DOCUMENT_UNSHARED',
    DOCUMENT_APPROVED: 'DOCUMENT_APPROVED',
    DOCUMENT_UNAPPROVED: 'DOCUMENT_UNAPPROVED',
    DOCUMENT_REJECTED: 'DOCUMENT_REJECTED',
    DOCUMENT_PUBLISHED: 'DOCUMENT_PUBLISHED',
    DOCUMENT_UNPUBLISHED: 'DOCUMENT_UNPUBLISHED',
    DOCUMENT_STASHED: 'DOCUMENT_STASHED',
    DOCUMENT_VIEWED: 'DOCUMENT_VIEWED',
    DOCUMENT_DOWNLOADED: 'DOCUMENT_DOWNLOADED',

    VERSION_CREATED: 'VERSION_CREATED',
    VERSION_REVERTED: 'VERSION_REVERTED',

    REQUEST_CREATED: 'REQUEST_CREATED',
    REQUEST_UPDATED: 'REQUEST_UPDATED',
    REQUEST_DELETED: 'REQUEST_DELETED',
    REQUEST_RESOLVED: 'REQUEST_RESOLVED',
    REQUEST_REJECTED: 'REQUEST_REJECTED',
    MESSAGE_CREATED: 'MESSAGE_CREATED',
    MESSAGE_UPDATED: 'MESSAGE_UPDATED',
    MESSAGE_DELETED: 'MESSAGE_DELETED',

    ATTACHMENT_CREATED: 'ATTACHMENT_CREATED',
    ATTACHMENT_DELETED: 'ATTACHMENT_DELETED',
    ATTACHMENT_VIEWED: 'ATTACHMENT_VIEWED',
    ATTACHMENT_DOWNLOADED: 'ATTACHMENT_DOWNLOADED',

    COORDINATOR_CREATED: 'COORDINATOR_CREATED',
    COORDINATOR_DELETED: 'COORDINATOR_DELETED',
    COORDINATOR_APPROVED: 'COORDINATOR_APPROVED',
    COORDINATOR_REJECTED: 'COORDINATOR_REJECTED',
});
