// ============================================================================
// PAMANTASAN DOCUMENT MANAGEMENT SYSTEM (DMS) — DATABASE CONSTANTS
// Canonical database schemas, domains, enums, regex patterns, and constraints.
// ============================================================================

// --- 1. TABLE & VIEW NAMES ---
export const DATABASE_TABLES = Object.freeze({
    DEPARTMENTS: 'departments',
    USERS: 'users',
    USER_CREDENTIALS: 'user_credentials',
    USER_SETTINGS: 'user_settings',
    USER_SESSIONS: 'user_sessions',
    DOCUMENTS: 'documents',
    DOCUMENT_VERSIONS: 'document_versions',
    DOCUMENT_SHARES: 'document_shares',
    DOCUMENT_REQUESTS: 'document_requests',
    DOCUMENT_REQUEST_MESSAGES: 'document_request_messages',
    DOCUMENT_REQUEST_ATTACHMENTS: 'document_request_attachments',
    COORDINATOR_REQUESTS: 'coordinator_requests',
    NOTIFICATIONS: 'notifications',
    AUDIT_LOGS: 'audit_logs',
});

export const DATABASE_VIEWS = Object.freeze({
    VIEW_NOTIFICATIONS: 'view_notifications',
});

// --- 2. USER ROLES (system_users_role) ---
export const USER_ROLES = Object.freeze({
    ADMINISTRATOR: 'ADMINISTRATOR',
    COORDINATOR: 'COORDINATOR',
    DIRECTOR: 'DIRECTOR',
    OFFICER: 'OFFICER',
    MEMBER: 'MEMBER',
});

export const USER_ROLE_LIST = Object.freeze([
    USER_ROLES.ADMINISTRATOR,
    USER_ROLES.COORDINATOR,
    USER_ROLES.DIRECTOR,
    USER_ROLES.OFFICER,
    USER_ROLES.MEMBER,
]);

export const USER_ROLE_HIERARCHY = Object.freeze({
    [USER_ROLES.ADMINISTRATOR]: 5,
    [USER_ROLES.COORDINATOR]: 4,
    [USER_ROLES.DIRECTOR]: 3,
    [USER_ROLES.OFFICER]: 2,
    [USER_ROLES.MEMBER]: 1,
});

export const USER_ROLE_LABELS = Object.freeze({
    [USER_ROLES.ADMINISTRATOR]: 'Administrator',
    [USER_ROLES.COORDINATOR]: 'Coordinator',
    [USER_ROLES.DIRECTOR]: 'Director / Department Head',
    [USER_ROLES.OFFICER]: 'Department Officer',
    [USER_ROLES.MEMBER]: 'Faculty / Member',
});

// --- 3. USER ACCOUNT STATUSES (system_users_status) ---
export const USER_STATUSES = Object.freeze({
    PENDING_PASSWORD: 'PENDING_PASSWORD',
    PENDING_SSO: 'PENDING_SSO',
    VERIFIED: 'VERIFIED',
    SUSPENDED: 'SUSPENDED',
});

export const USER_STATUS_LIST = Object.freeze([
    USER_STATUSES.PENDING_PASSWORD,
    USER_STATUSES.PENDING_SSO,
    USER_STATUSES.VERIFIED,
    USER_STATUSES.SUSPENDED,
]);

export const DEFAULT_USER_STATUS = USER_STATUSES.PENDING_PASSWORD;

// --- 4. USER SETTINGS THEMES (system_user_settings_theme) ---
export const THEME_MODES = Object.freeze({
    SYSTEM: 'SYSTEM',
    LIGHT: 'LIGHT',
    DARK: 'DARK',
});

export const THEME_MODE_LIST = Object.freeze([
    THEME_MODES.SYSTEM,
    THEME_MODES.LIGHT,
    THEME_MODES.DARK,
]);

export const DEFAULT_THEME_MODE = THEME_MODES.SYSTEM;

// --- 5. USER SETTINGS NOTIFICATION SCOPES (system_user_settings_notification) ---
export const NOTIFICATION_SCOPES = Object.freeze({
    ALL: 'ALL',
    SYSTEM: 'SYSTEM',
    IMPORTANT: 'IMPORTANT',
});

export const NOTIFICATION_SCOPE_LIST = Object.freeze([
    NOTIFICATION_SCOPES.ALL,
    NOTIFICATION_SCOPES.SYSTEM,
    NOTIFICATION_SCOPES.IMPORTANT,
]);

export const DEFAULT_NOTIFICATION_SCOPE = NOTIFICATION_SCOPES.ALL;

// --- 6. DOCUMENT CLASSIFICATIONS (system_document_versions_classification) ---
export const DOCUMENT_TYPES = Object.freeze({
    FILE: 'FILE',
    FOLDER: 'FOLDER',
});

export const DOCUMENT_CLASSIFICATIONS = Object.freeze({
    UNCLASSIFIED: 'UNCLASSIFIED',
    PUBLIC: 'PUBLIC',
    PRIVATE: 'PRIVATE',
    CONFIDENTIAL: 'CONFIDENTIAL',
    RESTRICTED: 'RESTRICTED',
});

export const DOCUMENT_CLASSIFICATION_LIST = Object.freeze([
    DOCUMENT_CLASSIFICATIONS.UNCLASSIFIED,
    DOCUMENT_CLASSIFICATIONS.PUBLIC,
    DOCUMENT_CLASSIFICATIONS.PRIVATE,
    DOCUMENT_CLASSIFICATIONS.CONFIDENTIAL,
    DOCUMENT_CLASSIFICATIONS.RESTRICTED,
]);

export const DEFAULT_DOCUMENT_CLASSIFICATION = DOCUMENT_CLASSIFICATIONS.UNCLASSIFIED;

// --- 7. DOCUMENT SHARE STATUSES (system_document_shares_status) ---
export const DOCUMENT_SHARE_STATUSES = Object.freeze({
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    APPROVED: 'APPROVED',
    PUBLISHED: 'PUBLISHED',
    STASHED: 'STASHED',
});

export const DOCUMENT_SHARE_STATUS_LIST = Object.freeze([
    DOCUMENT_SHARE_STATUSES.PENDING_APPROVAL,
    DOCUMENT_SHARE_STATUSES.APPROVED,
    DOCUMENT_SHARE_STATUSES.PUBLISHED,
    DOCUMENT_SHARE_STATUSES.STASHED,
]);

export const DEFAULT_DOCUMENT_SHARE_STATUS = DOCUMENT_SHARE_STATUSES.PENDING_APPROVAL;

// --- 8. SHARE STATUS TRANSITION RULES ---
export const OFFICER_ALLOWED_SHARE_TRANSITIONS = Object.freeze([
    { from: DOCUMENT_SHARE_STATUSES.PENDING_APPROVAL, to: DOCUMENT_SHARE_STATUSES.APPROVED },
    { from: DOCUMENT_SHARE_STATUSES.APPROVED, to: DOCUMENT_SHARE_STATUSES.PENDING_APPROVAL },
]);

export const DIRECTOR_ALLOWED_SHARE_TRANSITIONS = Object.freeze([
    { from: DOCUMENT_SHARE_STATUSES.APPROVED, to: DOCUMENT_SHARE_STATUSES.PUBLISHED },
    { from: DOCUMENT_SHARE_STATUSES.PUBLISHED, to: DOCUMENT_SHARE_STATUSES.APPROVED },
    { from: DOCUMENT_SHARE_STATUSES.APPROVED, to: DOCUMENT_SHARE_STATUSES.STASHED },
    { from: DOCUMENT_SHARE_STATUSES.STASHED, to: DOCUMENT_SHARE_STATUSES.APPROVED },
]);

// --- 9. DOCUMENT REQUEST STATUSES (system_document_requests_status) ---
export const DOCUMENT_REQUEST_STATUSES = Object.freeze({
    OPEN: 'OPEN',
    RESOLVED: 'RESOLVED',
    REJECTED: 'REJECTED',
});

export const DOCUMENT_REQUEST_STATUS_LIST = Object.freeze([
    DOCUMENT_REQUEST_STATUSES.OPEN,
    DOCUMENT_REQUEST_STATUSES.RESOLVED,
    DOCUMENT_REQUEST_STATUSES.REJECTED,
]);

export const DEFAULT_DOCUMENT_REQUEST_STATUS = DOCUMENT_REQUEST_STATUSES.OPEN;

// --- 10. COORDINATOR REQUEST ACTIONS (system_coordinator_requests_action) ---
export const COORDINATOR_REQUEST_ACTIONS = Object.freeze({
    USER_CREATE: 'USER_CREATE',
    USER_UPDATE: 'USER_UPDATE',
    USER_SUSPEND: 'USER_SUSPEND',
    DEPARTMENT_CREATE: 'DEPARTMENT_CREATE',
    DEPARTMENT_UPDATE: 'DEPARTMENT_UPDATE',
    DOCUMENT_UPLOAD: 'DOCUMENT_UPLOAD',
    DOCUMENT_UPDATE: 'DOCUMENT_UPDATE',
    DOCUMENT_DELETE: 'DOCUMENT_DELETE',
    DOCUMENT_SHARE: 'DOCUMENT_SHARE',
    DOCUMENT_ARCHIVE: 'DOCUMENT_ARCHIVE',
    DOCUMENT_ATTACH: 'DOCUMENT_ATTACH',
});

export const COORDINATOR_REQUEST_ACTION_LIST = Object.freeze([
    COORDINATOR_REQUEST_ACTIONS.USER_CREATE,
    COORDINATOR_REQUEST_ACTIONS.USER_UPDATE,
    COORDINATOR_REQUEST_ACTIONS.USER_SUSPEND,
    COORDINATOR_REQUEST_ACTIONS.DEPARTMENT_CREATE,
    COORDINATOR_REQUEST_ACTIONS.DEPARTMENT_UPDATE,
    COORDINATOR_REQUEST_ACTIONS.DOCUMENT_UPLOAD,
    COORDINATOR_REQUEST_ACTIONS.DOCUMENT_UPDATE,
    COORDINATOR_REQUEST_ACTIONS.DOCUMENT_DELETE,
    COORDINATOR_REQUEST_ACTIONS.DOCUMENT_SHARE,
    COORDINATOR_REQUEST_ACTIONS.DOCUMENT_ARCHIVE,
    COORDINATOR_REQUEST_ACTIONS.DOCUMENT_ATTACH,
]);

// --- 11. COORDINATOR REQUEST STATUSES (system_coordinator_requests_status) ---
export const COORDINATOR_REQUEST_STATUSES = Object.freeze({
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
});

export const COORDINATOR_REQUEST_STATUS_LIST = Object.freeze([
    COORDINATOR_REQUEST_STATUSES.PENDING,
    COORDINATOR_REQUEST_STATUSES.APPROVED,
    COORDINATOR_REQUEST_STATUSES.REJECTED,
]);

export const DEFAULT_COORDINATOR_REQUEST_STATUS = COORDINATOR_REQUEST_STATUSES.PENDING;

// --- 12. NOTIFICATION ENTITY TYPES (system_notifications_entity_type) ---
export const NOTIFICATION_ENTITY_TYPES = Object.freeze({
    USER: 'USER',
    DEPARTMENT: 'DEPARTMENT',
    DOCUMENT: 'DOCUMENT',
    COORDINATOR_REQUEST: 'COORDINATOR_REQUEST',
    DOCUMENT_REQUEST: 'DOCUMENT_REQUEST',
});

export const NOTIFICATION_ENTITY_TYPE_LIST = Object.freeze([
    NOTIFICATION_ENTITY_TYPES.USER,
    NOTIFICATION_ENTITY_TYPES.DEPARTMENT,
    NOTIFICATION_ENTITY_TYPES.DOCUMENT,
    NOTIFICATION_ENTITY_TYPES.COORDINATOR_REQUEST,
    NOTIFICATION_ENTITY_TYPES.DOCUMENT_REQUEST,
]);

// --- 13. AUDIT LOG ENTITY TYPES (system_audit_logs_entity_type) ---
export const AUDIT_LOG_ENTITY_TYPES = Object.freeze({
    USER: 'USER',
    DEPARTMENT: 'DEPARTMENT',
    DOCUMENT: 'DOCUMENT',
    DOCUMENT_VERSION: 'DOCUMENT_VERSION',
    DOCUMENT_SHARE: 'DOCUMENT_SHARE',
    DOCUMENT_REQUEST: 'DOCUMENT_REQUEST',
    DOCUMENT_REQUEST_ATTACHMENT: 'DOCUMENT_REQUEST_ATTACHMENT',
    COORDINATOR_REQUEST: 'COORDINATOR_REQUEST',
});

export const AUDIT_LOG_ENTITY_TYPE_LIST = Object.freeze([
    AUDIT_LOG_ENTITY_TYPES.USER,
    AUDIT_LOG_ENTITY_TYPES.DEPARTMENT,
    AUDIT_LOG_ENTITY_TYPES.DOCUMENT,
    AUDIT_LOG_ENTITY_TYPES.DOCUMENT_VERSION,
    AUDIT_LOG_ENTITY_TYPES.DOCUMENT_SHARE,
    AUDIT_LOG_ENTITY_TYPES.DOCUMENT_REQUEST,
    AUDIT_LOG_ENTITY_TYPES.DOCUMENT_REQUEST_ATTACHMENT,
    AUDIT_LOG_ENTITY_TYPES.COORDINATOR_REQUEST,
]);

// --- 14. SYSTEM ACTIONS (system_notifications_action / system_audit_logs_action) ---
export const SYSTEM_ACTIONS = Object.freeze({
    CREATED: 'CREATED',
    UPDATED: 'UPDATED',
    DELETED: 'DELETED',
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    APPROVED: 'APPROVED',
    UNAPPROVED: 'UNAPPROVED',
    REJECTED: 'REJECTED',
    STASHED: 'STASHED',
    UPLOADED: 'UPLOADED',
    SHARED: 'SHARED',
    UNSHARED: 'UNSHARED',
    PUBLISHED: 'PUBLISHED',
    UNPUBLISHED: 'UNPUBLISHED',
    ARCHIVED: 'ARCHIVED',
    UNARCHIVED: 'UNARCHIVED',
    RESOLVED: 'RESOLVED',
    COMMENTED: 'COMMENTED',
    ATTACHED: 'ATTACHED',
    SUSPENDED: 'SUSPENDED',
    UNSUSPENDED: 'UNSUSPENDED',
    REVERTED: 'REVERTED',
});

export const SYSTEM_ACTION_LIST = Object.freeze([
    SYSTEM_ACTIONS.CREATED,
    SYSTEM_ACTIONS.UPDATED,
    SYSTEM_ACTIONS.DELETED,
    SYSTEM_ACTIONS.PENDING_APPROVAL,
    SYSTEM_ACTIONS.APPROVED,
    SYSTEM_ACTIONS.UNAPPROVED,
    SYSTEM_ACTIONS.REJECTED,
    SYSTEM_ACTIONS.STASHED,
    SYSTEM_ACTIONS.UPLOADED,
    SYSTEM_ACTIONS.SHARED,
    SYSTEM_ACTIONS.UNSHARED,
    SYSTEM_ACTIONS.PUBLISHED,
    SYSTEM_ACTIONS.UNPUBLISHED,
    SYSTEM_ACTIONS.ARCHIVED,
    SYSTEM_ACTIONS.UNARCHIVED,
    SYSTEM_ACTIONS.RESOLVED,
    SYSTEM_ACTIONS.COMMENTED,
    SYSTEM_ACTIONS.ATTACHED,
    SYSTEM_ACTIONS.SUSPENDED,
    SYSTEM_ACTIONS.UNSUSPENDED,
    SYSTEM_ACTIONS.REVERTED,
]);

// --- 15. REGEX PATTERNS & FIELD VALIDATION CONSTRAINTS ---
export const VALIDATION_PATTERNS = Object.freeze({
    UNIVERSITY_ID: /^[0-9]{2}-[0-9]{5}$/,
    EMAIL: /^[A-Za-z0-9._%+-]+@plpasig\.edu\.ph$/,
    UUID: /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
});

export const INSTITUTIONAL_CONFIG = Object.freeze({
    EMAIL_DOMAIN: '@plpasig.edu.ph',
    VECTOR_DIMENSIONS: 768,
    CHECKSUM_HEX_LENGTH: 64,
    MAX_NAME_LENGTH: 255,
    MAX_CODE_LENGTH: 50,
    MAX_PATH_LENGTH: 512,
    MAX_MIME_TYPE_LENGTH: 100,
    MAX_USER_NAME_LENGTH: 100,
    MAX_UNIVERSITY_ID_LENGTH: 20,
});

// --- 16. INSTITUTIONAL DEPARTMENTS & ACADEMIC COLLEGES ---
export const DEFAULT_DEPARTMENTS = Object.freeze([
    { id: 'd1000001-0000-4000-8000-000000000001', code: 'RMO', name: 'Records Management Office' },
    { id: 'd1000002-0000-4000-8000-000000000002', code: 'CN', name: 'College of Nursing' },
    { id: 'd1000003-0000-4000-8000-000000000003', code: 'COE', name: 'College of Engineering' },
    { id: 'd1000004-0000-4000-8000-000000000004', code: 'CED', name: 'College of Education' },
    { id: 'd1000005-0000-4000-8000-000000000005', code: 'CCS', name: 'College of Computer Studies' },
    { id: 'd1000006-0000-4000-8000-000000000006', code: 'CAS', name: 'College of Arts and Science' },
    { id: 'd1000007-0000-4000-8000-000000000007', code: 'CBA', name: 'College of Business and Accountancy' },
    { id: 'd1000008-0000-4000-8000-000000000008', code: 'CHM', name: 'College of Hospitality Management' },
]);
