// --- SHARED DOMAIN CONSTANTS ---

const DOCUMENT_VERSIONS_CLASSIFICATION = Object.freeze({
    UNCLASSIFIED: 'UNCLASSIFIED',
    PUBLIC: 'PUBLIC',
    PRIVATE: 'PRIVATE',
    CONFIDENTIAL: 'CONFIDENTIAL',
    RESTRICTED: 'RESTRICTED',
});

const INSTITUTIONAL_DOMAIN = '@plpasig.edu.ph';

module.exports = {
    DOCUMENT_VERSIONS_CLASSIFICATION,
    INSTITUTIONAL_DOMAIN,
};
